### ISSUE TITLE
Is there a replacement for this utility?

### ISSUE THREAD

**Issue by jasonkarns** [chrmoritz/homebrew-node-formulator#1]
I am intending to create a brew external command `brew npm` which is a fork of `brew gem`.

https://github.com/sportngin/brew-gem
https://github.com/jasonkarns/brew-npm

brew-gem is a command that generates (on the fly) a homebrew formula based on a gem, with the intent of having system-wide, CLI like gems installed and managed through homebrew instead of rubygems.

I intend for brew-npm to do likewise for npm packages, such that global cli utilities can be installed outside of a particular node installation (solving the problem of having global modules across multiple nodes; eg, from nvm or nodenv, etc)

I see that you are the one responsible for `Language::Node`– thanks! And since this module (node-formulator) is essentially what I want brew-npm to do (but on the fly), I wanted to see you have any existing work in this regard.

Thanks!

**Comment by chrmoritz** [comment]
The intent of this project / experiment was to generate homebrew formulas for npm packages which can be installed without using the npm cli at all. It was motivated by the fact that homebrew normally prefers to manage all it's dependencies on it's own (using resources) and tries to avoid installation steps which download additional dependencies over the network (because it can't verify shasums this way).

The homebrew side code of this experiment can be found here: 
https://github.com/chrmoritz/homebrew-node (still a prototype)

It works by storing every npm dependency inside a slightly extended homebrew `resource`  (with parent information for non top level deps). As you can imagine this results in a lot of resources for big npm packages like [autocode](https://github.com/chrmoritz/homebrew-node/blob/master/Formula/autocode.rb) which was the reason for generating this formula generator.

But as it turned out homebrew wasn't written to handle this amount of resources (the installation was really slow because of the sequential resource installation). That's why this experiment was abandoned and I've created an alternative with the current `Language::Node` in homebrew.

Looking at `brew-gem` I don't think that you have the intent to move away from npm completely and just want to generate formulas on the fly which are calling npm with the 'Language::node' args (to generate a global style npm installation with a custom prefix of `libexec`). Unfortunately I have to say that there is not much you can reuse from this project if that is the case (everything related is still aprt of `Language::Node`).

**Comment by jasonkarns** [comment]
> I don't think that you have the intent to move away from npm completely and just want to generate formulas on the fly

Exactly. brew-npm is intended to be an external command and not intended to generate formulas that will end up in homebrew. Though it _is_ generating formulas, they are temporary formulas that only exist for the duration of the installation, and are then removed. (never ending up in homebrew at all)

It is side-stepping homebrew's typical conventions. However, I'm modeling it after the existing brew-gem command which seems to already be sort of blessed by the core team.

I'm most excited about Language::Node existing because that logic would have needed to live in brew-npm, but now it's in brew core! (thanks again for that)

> Unfortunately I have to say that there is not much you can reuse from this project if that is the case

No worries. Thought I'd ask.
